theme: jekyll-theme-minimal
title: "SGN Documentation"
description: <form action="search.html"><input type="text" placeholder="Search" name="q" id="tipue_search_input" pattern=".{3,}" title="At least 3 characters" required></form>
